# Generated by Django 4.2.4 on 2023-08-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0004_rehomer_delete_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='vaccination',
            field=models.CharField(max_length=50),
        ),
    ]
